excellentSkills:
  female:
    - dagger
    - siege

individualDiff:
  raises: 4
  skill:
    points: 10
    max: 15
    excellent: 15
    extra: 
      value: 10
      count: 3
    raise: 5
    noCombatPoints: 10
  trait:
    famous: 16
    points: 6
  passion:
    points: 3

points:
  attributes: 60
  traitsRandom: 3
  
max:
  trait: 19
  passion: 20

rolls:
  homelandPassion: 4d6+1
  commonPassion: 3d6+4
  trait: 3d6
  directedTrait: 1d6+1
  femaleValorousMod: 1d6+3

attributeRolls:
  male:
    appearance: 3d6+1
    constitution: 3d6+1
    dexterity: 3d6+1
    size: 3d6+4
    strength: 3d6+1
  female:
    appearance: 3d6+5
    constitution: 3d6+1
    dexterity: 3d6+1
    size: 2d6+2
    strength: 2d6+2

glory:
  knight: 6d6+150
  
religion:
  traitBonus: 3