- name: awareness
- name: axe
- name: battle
- name: boating
- name: bow
- name: charioteer
- name: chirurgery
- name: compose
- name: compound_bow
- name: courtesy
- name: crossbow
- name: dagger
- name: dancing
- name: faerie_lore
- name: falconry
- name: fashion
- name: first_aid
- name: flail
- name: flirting
- name: folklore
- name: gaming
- name: grapple
- name: great_axe
- name: great_lance
- name: great_mace
- name: great_spear
- name: great_sword
- name: halberd
- name: hammer
- name: heraldry
- name: horsemanship
- name: hunting
- name: industry
- name: intrigue
- name: javelin
- name: lance
- name: mace
- name: morning_star
- name: orate
- name: recognize
- name: romance
- name: siege
- name: singing
- name: spear
- name: stewardship
- name: sword
- name: swimming
- name: tourney
- name: warflail